export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED';
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

export const AUTH_REQUEST_LOAD = 'AUTH_REQUEST_LOAD';
export const AUTH_REQUEST_SUCCESS = 'AUTH_REQUEST_SUCCESS';
export const AUTH_REQUEST_FAILED = 'AUTH_REQUEST_FAILED';